#!/bin/bash

# =============================================================================
# WeeVoice Deployment Script (No Docker)
# =============================================================================
# 
# Prerequisites:
#   1. Ubuntu 20.04/22.04 VPS with Asterisk installed
#   2. Domain pointing to VPS (or use IP for testing)
#   3. backend/.env file with GOOGLE_API_KEY configured
#
# Usage:
#   cd deploy
#   sudo ./deploy-no-docker.sh weevoice.weedoo.be
#
# =============================================================================

set -e

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

log_info() { echo -e "${GREEN}[INFO]${NC} $1"; }
log_warn() { echo -e "${YELLOW}[WARN]${NC} $1"; }
log_error() { echo -e "${RED}[ERROR]${NC} $1"; }

echo ""
echo "============================================"
echo "  WeeVoice Deployment (No Docker)"
echo "============================================"
echo ""

# Check if running as root
if [ "$EUID" -ne 0 ]; then
    log_error "Please run as root: sudo ./deploy-no-docker.sh <domain>"
    exit 1
fi

# Get domain from argument or prompt
DOMAIN=${1:-}
if [ -z "$DOMAIN" ]; then
    log_error "Usage: sudo ./deploy-no-docker.sh <domain_or_ip>"
    log_error "Example: sudo ./deploy-no-docker.sh weevoice.weedoo.be"
    exit 1
fi

# Check for .env file (try multiple locations)
ENV_FILE=""
if [ -f "env-templates/backend.env" ]; then
    ENV_FILE="env-templates/backend.env"
elif [ -f "../backend/.env" ]; then
    ENV_FILE="../backend/.env"
fi

if [ -z "$ENV_FILE" ]; then
    log_error "No .env file found!"
    log_error "Please create deploy/env-templates/backend.env or backend/.env"
    exit 1
fi

log_info "Loading configuration from $ENV_FILE"
source "$ENV_FILE"

# Validate GOOGLE_API_KEY
if [ -z "$GOOGLE_API_KEY" ]; then
    log_error "GOOGLE_API_KEY not found in backend/.env"
    exit 1
fi

# Generate SECRET_KEY if not set
SECRET_KEY=${SECRET_KEY:-$(openssl rand -hex 32)}

# Determine protocol
if [[ $DOMAIN =~ ^[0-9]+\.[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
    PROTOCOL="http"
    USE_SSL=false
    log_warn "IP address detected - using HTTP (no SSL)"
else
    PROTOCOL="https"
    USE_SSL=true
fi

log_info "Domain: $DOMAIN"
log_info "Protocol: $PROTOCOL"
log_info "Google API Key: ${GOOGLE_API_KEY:0:15}..."

# =============================================================================
# Step 1: Install Dependencies
# =============================================================================
log_info "Step 1/8: Installing system dependencies..."

apt-get update -qq
apt-get install -y -qq python3 python3-venv python3-pip nginx certbot python3-certbot-nginx supervisor curl > /dev/null

# Install Node.js 22
if ! command -v node &> /dev/null || ! node -v | grep -q "v22"; then
    log_info "Installing Node.js 22..."
    curl -fsSL https://deb.nodesource.com/setup_22.x | bash - > /dev/null 2>&1
    apt-get install -y -qq nodejs > /dev/null
fi

# =============================================================================
# Step 2: Create Directory Structure
# =============================================================================
log_info "Step 2/8: Setting up directories..."

mkdir -p /opt/weevoice/{backend,frontend,data,uploads}
mkdir -p /var/log/weevoice

# Copy application files
cp -r ../backend/* /opt/weevoice/backend/
cp -r ../frontend/* /opt/weevoice/frontend/

# =============================================================================
# Step 3: Setup Backend
# =============================================================================
log_info "Step 3/8: Setting up backend..."

cd /opt/weevoice/backend

# Create virtual environment and install dependencies
python3 -m venv venv
./venv/bin/pip install --upgrade pip -q
./venv/bin/pip install -r requirements.txt -q

# Create production .env (preserving all original values + overriding URLs)
cat > .env << EOF
# =============================================================================
# WeeVoice Backend - Production (auto-generated by deploy script)
# =============================================================================

# Core Settings
DEBUG=false
SECRET_KEY=$SECRET_KEY
BASE_URL=$PROTOCOL://$DOMAIN
FRONTEND_URL=$PROTOCOL://$DOMAIN
BACKEND_URL=$PROTOCOL://$DOMAIN/api
BACKEND_CORS_ORIGINS=["$PROTOCOL://$DOMAIN","http://localhost:3000"]

# Database
DATABASE_URL=${DATABASE_URL:-sqlite:////opt/weevoice/data/voiceagent.db}

# AI APIs
GOOGLE_API_KEY=$GOOGLE_API_KEY
OPENAI_API_KEY=${OPENAI_API_KEY:-}
OPENAI_SUMMARY_MODEL=${OPENAI_SUMMARY_MODEL:-gpt-4o}

# Storage (Supabase)
STORAGE_URL=${STORAGE_URL:-}
STORAGE_KEY=${STORAGE_KEY:-}
STORAGE_BUCKET=${STORAGE_BUCKET:-weevoice}

# Email (SMTP)
SMTP_HOST=${SMTP_HOST:-}
SMTP_PORT=${SMTP_PORT:-587}
SMTP_USER=${SMTP_USER:-}
SMTP_PASSWORD=${SMTP_PASSWORD:-}
SMTP_USE_TLS=${SMTP_USE_TLS:-1}
SMTP_FROM_EMAIL=${SMTP_FROM_EMAIL:-}
SMTP_FROM_NAME=${SMTP_FROM_NAME:-WeeVoice}

# Zadarma Integration
ZADARMA_API_KEY=${ZADARMA_API_KEY:-}
ZADARMA_API_SECRET=${ZADARMA_API_SECRET:-}

# SIP / AudioSocket
SIP_ENABLED=true

# Pricing
COST_PER_MINUTE=${COST_PER_MINUTE:-0.07}
PHONE_NUMBER_MONTHLY_COST=${PHONE_NUMBER_MONTHLY_COST:-4.99}

# Storage Paths (auto-set for VPS)
UPLOAD_DIR=/opt/weevoice/uploads
CALL_RECORDINGS_PATH=/opt/weevoice/data/recordings
TRANSCRIPTS_PATH=/opt/weevoice/data/transcripts

# Stripe (optional)
STRIPE_SECRET_KEY=${STRIPE_SECRET_KEY:-}
STRIPE_PUBLISHABLE_KEY=${STRIPE_PUBLISHABLE_KEY:-}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET:-}
EOF

# =============================================================================
# Step 4: Setup Frontend
# =============================================================================
log_info "Step 4/8: Setting up frontend..."

cd /opt/weevoice/frontend

# Create frontend .env (Vite uses VITE_ prefix)
cat > .env.local << EOF
VITE_API_URL=$PROTOCOL://$DOMAIN/api
EOF

# Install and build (use yarn if yarn.lock exists, otherwise npm)
if [ -f "yarn.lock" ]; then
    log_info "Using Yarn..."
    npm install -g yarn > /dev/null 2>&1
    yarn install --frozen-lockfile
    yarn build
else
    npm ci --silent
    npm run build --silent
fi

# =============================================================================
# Step 5: Configure Supervisor
# =============================================================================
log_info "Step 5/8: Configuring process manager..."

cat > /etc/supervisor/conf.d/weevoice.conf << EOF
[program:weevoice-backend]
command=/opt/weevoice/backend/venv/bin/uvicorn app.main:app --host 127.0.0.1 --port 8000
directory=/opt/weevoice/backend
user=www-data
autostart=true
autorestart=true
stderr_logfile=/var/log/weevoice/backend.err.log
stdout_logfile=/var/log/weevoice/backend.out.log

[program:weevoice-frontend]
command=/usr/bin/npx vite preview --host 127.0.0.1 --port 3000
directory=/opt/weevoice/frontend
user=www-data
autostart=true
autorestart=true
stderr_logfile=/var/log/weevoice/frontend.err.log
stdout_logfile=/var/log/weevoice/frontend.out.log
environment=NODE_ENV="production"
EOF

chown -R www-data:www-data /opt/weevoice /var/log/weevoice

# =============================================================================
# Step 6: Configure Nginx
# =============================================================================
log_info "Step 6/8: Configuring Nginx..."

if [ "$USE_SSL" = true ]; then
    # HTTPS config (SSL will be added by certbot)
    cat > /etc/nginx/sites-available/weevoice << EOF
server {
    listen 80;
    server_name $DOMAIN;
    
    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 86400;
    }

    location /api/v1/ws/ {
        proxy_pass http://127.0.0.1:8000/api/v1/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_read_timeout 86400;
    }
}
EOF
else
    # HTTP only config (for IP address)
    cat > /etc/nginx/sites-available/weevoice << EOF
server {
    listen 80;
    server_name $DOMAIN;

    location / {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
    }

    location /api/ {
        proxy_pass http://127.0.0.1:8000/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_read_timeout 86400;
    }

    location /api/v1/ws/ {
        proxy_pass http://127.0.0.1:8000/api/v1/ws/;
        proxy_http_version 1.1;
        proxy_set_header Upgrade \$http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_set_header Host \$host;
        proxy_read_timeout 86400;
    }
}
EOF
fi

ln -sf /etc/nginx/sites-available/weevoice /etc/nginx/sites-enabled/
rm -f /etc/nginx/sites-enabled/default
nginx -t -q

# =============================================================================
# Step 7: SSL Certificate (if domain)
# =============================================================================
if [ "$USE_SSL" = true ]; then
    log_info "Step 7/8: Getting SSL certificate..."
    certbot --nginx -d $DOMAIN --non-interactive --agree-tos --email admin@$DOMAIN 2>/dev/null || {
        log_warn "SSL failed - you can run manually: certbot --nginx -d $DOMAIN"
    }
else
    log_info "Step 7/8: Skipping SSL (using IP address)..."
fi

# =============================================================================
# Step 8: Start Services
# =============================================================================
log_info "Step 8/8: Starting services..."

systemctl restart nginx
supervisorctl reread > /dev/null
supervisorctl update > /dev/null
supervisorctl restart weevoice-backend weevoice-frontend 2>/dev/null || supervisorctl start all

# Configure firewall (if ufw is active)
if command -v ufw &> /dev/null && ufw status | grep -q "active"; then
    ufw allow 80/tcp > /dev/null
    ufw allow 443/tcp > /dev/null
    ufw allow 5060/udp > /dev/null
    ufw allow 8089/tcp > /dev/null
fi

# =============================================================================
# Done!
# =============================================================================
echo ""
echo "============================================"
echo -e "  ${GREEN}Deployment Complete!${NC}"
echo "============================================"
echo ""
echo "URLs:"
echo "  Frontend: $PROTOCOL://$DOMAIN"
echo "  API:      $PROTOCOL://$DOMAIN/api"
echo "  API Docs: $PROTOCOL://$DOMAIN/api/docs"
echo ""
echo "AudioSocket: 127.0.0.1:9092"
echo ""
echo "Commands:"
echo "  Status:  supervisorctl status"
echo "  Logs:    tail -f /var/log/weevoice/backend.out.log"
echo "  Restart: supervisorctl restart weevoice-backend weevoice-frontend"
echo ""
echo "Asterisk extensions.conf:"
echo '  AudioSocket(${CALL_UUID},127.0.0.1:9092)'
echo ""
